apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filepvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: myvolume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvolume
  labels:
    type: local
    name: myvolume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp"